name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      run: |
        rustup update --no-self-update stable
        rustup component add rustfmt

    - name: Run fmt
      run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      run: |
        rustup update --no-self-update stable
        rustup component add clippy

    - name: Run clippy
      run: cargo clippy --all-features -- -D warnings

  test:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: cargo test --all-features

  msrv:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      run: rustup default 1.45.2

    - name: Run tests
      run: cargo test --all-features

  coverage:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cargo-tarpaulin
      run: |
        LINK="https://github.com/xd009642/tarpaulin/releases/download/0.16.0/cargo-tarpaulin-0.16.0-travis.tar.gz"
        curl -L --output tarpaulin.tar.gz "$LINK"
        tar -xzvf tarpaulin.tar.gz
        chmod +x cargo-tarpaulin

    - name: Run cargo-tarpaulin
      run: ./cargo-tarpaulin tarpaulin --all-features --out Xml

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
